### ISSUE TITLE
error sign

### ISSUE THREAD

**Issue by SuperKali** [Muqsit/SkyWars#8]
with this error [16:01:06] [Server thread/CRITICAL]: Unhandled exception executing command 'sw join test' in skywars: Call to a member function setText() on null
[16:01:06] [Server thread/CRITICAL]: Error: "Call to a member function setText() on null" (EXCEPTION) in "plugins/SkyWars-master/src/muqsit/skywars/handler/SignHandler" at line 100

**Comment by Muqsit** [comment]
This has already been fixed in https://github.com/Muqsit/SkyWars/commit/1f67518967f46b23592fcb414df488294ce5b2fc

**Comment by SuperKali** [comment]
@Muqsit no, I confirm that the problem still persists on the current version

**Comment by SuperKali** [comment]
i tested now

**Comment by SuperKali** [comment]
`[16:12:35] [Server thread/CRITICAL]: Could not execute task muqsit\skywars\game\tasks\CountdownTask: Call to a member function setText() on null
[16:12:35] [Server thread/CRITICAL]: Error: "Call to a member function setText() on null" (EXCEPTION) in "plugins/SkyWars-master/src/muqsit/skywars/handler/SignHandler" at line 100
[16:12:35] [Server thread/DEBUG]: #0 plugins/SkyWars-master/src/muqsit/skywars/game/SkyWars(607): muqsit\skywars\handler\SignHandler->updateSigns(muqsit\skywars\game\SkyWars object)
[16:12:35] [Server thread/DEBUG]: #1 plugins/SkyWars-master/src/muqsit/skywars/game/SkyWars(660): muqsit\skywars\game\SkyWars->setState(integer 2)
[16:12:35] [Server thread/DEBUG]: #2 plugins/SkyWars-master/src/muqsit/skywars/game/tasks/CountdownTask(20): muqsit\skywars\game\SkyWars->start()
[16:12:35] [Server thread/DEBUG]: #3 src/pocketmine/scheduler/TaskHandler(160): muqsit\skywars\game\tasks\CountdownTask->onRun(integer 18469)
[16:12:35] [Server thread/DEBUG]: #4 src/pocketmine/scheduler/ServerScheduler(248): pocketmine\scheduler\TaskHandler->run(integer 18469)
[16:12:35] [Server thread/DEBUG]: #5 src/pocketmine/Server(2525): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 18469)
[16:12:35] [Server thread/DEBUG]: #6 src/pocketmine/Server(2276): pocketmine\Server->tick()
[16:12:35] [Server thread/DEBUG]: #7 src/pocketmine/Server(2150): pocketmine\Server->tickProcessor()
[16:12:35] [Server thread/DEBUG]: #8 src/pocketmine/Server(1733): pocketmine\Server->start()
[16:12:35] [Server thread/DEBUG]: #9 src/pocketmine/PocketMine(290): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/Lobby-SW1/, string /root/Lobby-SW1/plugins/)
[16:13:56] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'SkyWars v1.0.0': Call to a member function setText() on null on muqsit\skywars\game\SkyWarsListener
[16:13:56] [Server thread/CRITICAL]: Error: "Call to a member function setText() on null" (EXCEPTION) in "plugins/SkyWars-master/src/muqsit/skywars/handler/SignHandler" at line 100
[16:13:56] [Server thread/DEBUG]: #0 plugins/SkyWars-master/src/muqsit/skywars/game/SkyWars(479): muqsit\skywars\handler\SignHandler->updateSigns(muqsit\skywars\game\SkyWars object)
[16:13:56] [Server thread/DEBUG]: #1 plugins/SkyWars-master/src/muqsit/skywars/game/SkyWars(361): muqsit\skywars\game\SkyWars->remove(pocketmine\Player object, boolean 1)
[16:13:56] [Server thread/DEBUG]: #2 plugins/SkyWars-master/src/muqsit/skywars/game/SkyWars(552): muqsit\skywars\game\SkyWars->reset()
[16:13:56] [Server thread/DEBUG]: #3 plugins/SkyWars-master/src/muqsit/skywars/game/SkyWars(475): muqsit\skywars\game\SkyWars->updateGameState()
[16:13:56] [Server thread/DEBUG]: #4 plugins/SkyWars-master/src/muqsit/skywars/game/SkyWarsListener(46): muqsit\skywars\game\SkyWars->remove(pocketmine\Player object)
[16:13:56] [Server thread/DEBUG]: #5 src/pocketmine/plugin/MethodEventExecutor(38): muqsit\skywars\game\SkyWarsListener->onPlayerQuit(pocketmine\event\player\PlayerQuitEvent object)
[16:13:56] [Server thread/DEBUG]: #6 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(muqsit\skywars\game\SkyWarsListener object, pocketmine\event\player\PlayerQuitEvent object)
[16:13:56] [Server thread/DEBUG]: #7 src/pocketmine/plugin/PluginManager(701): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerQuitEvent object)
[16:13:56] [Server thread/DEBUG]: #8 src/pocketmine/Player(3359): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerQuitEvent object)
[16:13:56] [Server thread/DEBUG]: #9 src/pocketmine/network/mcpe/RakLibInterface(116): pocketmine\Player->close(pocketmine\lang\TranslationContainer object, string timeout)
[16:13:56] [Server thread/DEBUG]: #10 vendor/pocketmine/raklib/server/ServerHandler(130): pocketmine\network\mcpe\RakLibInterface->closeSession(string 80.116.232.205 49287, string timeout)
[16:13:56] [Server thread/DEBUG]: #11 src/pocketmine/network/mcpe/RakLibInterface(103): raklib\server\ServerHandler->handlePacket()
[16:13:56] [Server thread/DEBUG]: #12 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
[16:13:56] [Server thread/DEBUG]: #13 src/pocketmine/network/mcpe/RakLibInterface(80): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
[16:13:56] [Server thread/DEBUG]: #14 vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[16:13:56] [Server thread/DEBUG]: #15 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
[16:13:56] [Server thread/DEBUG]: #16 src/pocketmine/Server(2279): pocketmine\snooze\SleeperHandler->sleepUntil(double 1527696836.8648)
[16:13:56] [Server thread/DEBUG]: #17 src/pocketmine/Server(2150): pocketmine\Server->tickProcessor()
[16:13:56] [Server thread/DEBUG]: #18 src/pocketmine/Server(1733): pocketmine\Server->start()
[16:13:56] [Server thread/DEBUG]: #19 src/pocketmine/PocketMine(290): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/Lobby-SW1/, string /root/Lobby-SW1/plugins/)
`

**Comment by SuperKali** [comment]
[16:17:41] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'SkyWars v1.0.0': Argument 1 passed to pocketmine\lang\BaseLang::translate() must be an instance of pocketmine\lang\TextContainer, string given, called in /root/Lobby-SW1/plugins/SkyWars-master/src/muqsit/skywars/game/SkyWarsListener.php on line 63 on muqsit\skywars\game\SkyWarsListener
[16:17:41] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\lang\BaseLang::translate() must be an instance of pocketmine\lang\TextContainer, string given, called in /root/Lobby-SW1/plugins/SkyWars-master/src/muqsit/skywars/game/SkyWarsListener.php on line 63" (EXCEPTION) in "src/pocketmine/lang/BaseLang" at line 121

**Comment by SuperKali** [comment]
@Muqsit read
